import LocalizedStrings from "react-native-localization";

let strings = new LocalizedStrings({
      en: {
         onboarding1title: `Gain total control\nof your money`,
         onboarding1text: `Become your own money manager\nand make every cent count`,
         onboarding2title: `Know where your\nmoney goes`,
         onboarding2text: `Track your transaction easily,\nwith categories and financial report`,
         onboarding3title: `Planning ahead`,
         onboarding3text: `Setup your budget for each category\nso you in control`,
         signup: `Sign Up`,
         login: `Login`,
         signupwithgoogle: `Sign Up with Google`,
         orwith: `Or with`,
         forgotpassword: `Forgot Password`,
         dontaccount: `Don’t have an account yet?`,
         haveaccount: `Already have an account?`,
         password: `Password`,
         name: `Name`,
         termsofservices1: `By signing up, you agree to the`,
         termsofservices2: `Terms of Service and Privacy Policy`,
         dontworry: `Don’t worry.\nEnter your email and we’ll send you a link to reset your password.`,
         continue: `Continue`,
         emailway: `Your email is on the way`,
         emailwaytext: `Check your email test@test.com and follow the instructions to reset your password`,
         gogmail: `Go to Gmail`,
         setuppin: `Let’s  setup your PIN`,
         resetuppin: `Ok. Re type your PIN again`,
         enterpin: `Enter PIN`,
         mismatchedpin: `The entered PINs do not match. Please try again`,
         incorrectpin: `PIN code is incorrect`,
         required: `Required`,
         erroremail: `Enter a valid email address`,
         errorpassword: `Enter a password of 6-16 characters`,
         errorname: `Enter a name of 3-16 letters [A-Z]-[a-z]`,
         incorrect: `Incorrect email or password`,
         loading: `Loading`,
         totalbalance: `Total Balance`,
         income: `Income`,
         expense: `Expense`,
         spendfrequency: `Spend Frequency`,
         short: `Short`,
         wide: `Wide`,
         recenttransactions: `Recent Transactions`,
         seeall: `See All`,
         notification: `Notification`,
         nonotification: `There is no notification for now`,
         markallread: `Mark all read`,
         removeall: `Remove all`,
         foodanddrink: `Food and Drink`,
         transportation: `Transportation`,
         shopping: `Shopping`,
         entertainment: `Entertainment`,
         personalcareandhealth: `Personal care and Health`,
         housing: `Housing`,
         creditanddebt: `Credit and Dept`,
         education: `Education`,
         savingsandinvestments: `Savings and Investments`,
         salary: `Salary`,
         sales: `Sales`,
         scholarship: `Scholarship`,
         refunds: `Refunds`,
         prizeoraward: `Prize or Award`,
         passiveincome: `Passive Income`,
         transfer: `Transfer`,
         seeyourfinancialreport: `See your financial report`,
         week: `Week`,
         month: `Month`,
         year: `Year`,
         highest: `Highest`,
         lowest: `Lowest`,
         newest: `Newest`,
         oldest: `Oldest`,
         reset: `Reset`,
         filtertransaction: `Filter Transaction`,
         filterby: `Filter By`,
         sortby: `Sort By`,
         category: `Category`,
         choosecategory: `Choose Category`,
         selected: `Selected`,
         apply: `Apply`,
         type: `Type`,
         wallet: `Wallet`,
         description: `Description`,
         from: `From`,
         to: `To`,
         edit: `Edit`,
         detailtransaction: `Detail Transaction`,
         nomoneytransaction: `No money transaction`,
         nomoneytransactionrecently: `There have been no transactions recently`,
         today: `Today`,
         yesterday: `Yesterday`,
         thismonth: `This Month`,
         youspend: `You Spend 💸`,
         youearned: `You Earned 💰`,
         biggestspend: `And your biggest\nspending is from`,
         biggestincome: `Your biggest\nIncome is from`,
         proverb: `“Financial freedom is freedom from fear.”`,
         proverbname: `-Robert Kiyosaki`,
         fulldetail: `See the full detail`,
         financialreport: `Financial Report`,
         account: `Account`,
         howmuch: `How Much?`,
         transactionsuccess: `Transaction has been successfully`,
         accountsuccess: `Account has been successfully`,
         added: `added`,
         updated: `updated`,
         removed: `removed`,
         removetransactiontitle: `Remove this transaction?`,
         removetransactiondescription: `Are you sure do you wanna remove this\ntransaction?`,
         yes: `Yes`,
         no: `No`,
         username: `Username`,
         settings: `Settings`,
         exportdata: `Export Data`,
         logout: `Logout`,
         logoutdescription: `Are you sure do you wanna logout?`,
         usernameupdated: `Username has been successfully updated`,
         addnewaccount: `Add new account`,
         accounttype: `Account Type`,
         balance: `Balance`,
         cash: `Cash`,
         creditcard: `Credit card`,
         savings: `Savings`,
         investment: `Investment`,
         business: `Business`,
         othermiscellaneous: `Other/miscellaneous`,
         editaccount: `Edit account`,
         detailaccount: `Detail account`,
         currency: `Currency`,
         language: `Language`,
         theme: `Theme`,
         about: `About`,
         help: `Help`,
         light: `Light`,
         dark: `Dark`,
         usedevicetheme: `Use device theme`,
         expensealert: `Expense Alert`,
         expensealerttext: `Get notification about you’re expense`,
         budgettext: `Get notification when you’re budget exceeding the limit`,
         tipsarticles: `Tips & Articles`,
         tipsarticlestext: `Small & useful pieces of pratical financial advice`,
         home: `Home`,
         transaction: `Transaction`,
         budget: `Budget`,
         profile: `Profile`,
      },
      az: {
         onboarding1title: `Pulunuza tam\nnəzarət edin`,
         onboarding1text: `Öz pul meneceriniz olun və hər\nqəpiyin hesabını yaradın`,
         onboarding2title: `Pulunuzun hara\ngetdiyini bilin`,
         onboarding2text: `Kateqoriyalar və maliyyə hesabatı ilə\nəməliyyatınızı asanlıqla izləyin`,
         onboarding3title: `Öncədən planlaşdırma`,
         onboarding3text: `Hər bir kateqoriya üçün büdcənizi\nqurun ki, nəzarət sizdə olsun`,
         signup: `Qeydiyyat`,
         login: `Giriş`,
         signupwithgoogle: `Google ilə Qeydiyyat`,
         orwith: `Və ya`,
         forgotpassword: `Şifrəni unutmusunuz`,
         dontaccount: `Hələ hesabınız yoxdur?`,
         haveaccount: `Artıq bir hesabınız var mı?`,
         password: `Şifrə`,
         name: `Ad`,
         termsofservices1: `Qeydiyyatdan keçməklə siz`,
         termsofservices2: `Xidmət Şərtləri və Məxfilik Siyasəti ilə razılaşırsınız`,
         dontworry: `Narahat olmayın.\nE-poçtunuzu daxil edin və biz sizə parolunuzu sıfırlamaq üçün link göndərəcəyik.`,
         continue: `Davam et`,
         emailway: `E-poçtunuz yoldadır`,
         emailwaytext: `test@test.com e-poçtunuzu yoxlayın və parolunuzu sıfırlamaq üçün təlimatlara əməl edin`,
         gogmail: `Gmail-ə gedin`,
         setuppin: `PİN kodunuzu təyin edin`,
         resetuppin: `PİN kodunuzu yenidən daxil edin`,
         enterpin: `PIN kodu daxil edin`,
         mismatchedpin: `Daxil edilmiş PIN-lər uyğun gəlmir. Zəhmət olmasa bir daha cəhd edin`,
         incorrectpin: `PIN kodu səhvdir`,
         required: `Zəruri`,
         erroremail: `Etibarlı e-poçt ünvanı daxil edin`,
         errorpassword: `6-16 simvoldan ibarət parol daxil edin`,
         errorname: `3-16 hərfdən ibarət ad daxil edin [A-Z]-[a-z]`,
         incorrect: `Yanlış e-poçt və ya parol`,
         loading: `Gözləyin`,
         totalbalance: `Toplam Balans`,
         income: `Gəlir`,
         expense: `Xərc`,
         spendfrequency: `Xərcləmə Tezliyi`,
         short: `Qısa`,
         wide: `Geniş`,
         recenttransactions: `Son Əməliyyatlar`,
         seeall: `Hamısını gör`,
         notification: `Bildirişlər`,
         nonotification: `Hələlik bildiriş yoxdur`,
         markallread: `Hamısını oxu`,
         removeall: `Hamısını sil`,
         foodanddrink: `Qida və içki`,
         transportation: `Nəqliyyat`,
         shopping: `Alış-veriş`,
         entertainment: `Əyləncə`,
         personalcareandhealth: `Şəxsi qayğı və Sağlamlıq`,
         housing: `Mənzil`,
         creditanddebt: `Kredit və borc`,
         education: `Təhsil`,
         savingsandinvestments: `Əmanətlər və İnvestisiyalar`,
         salary: `Maaş`,
         sales: `Satış`,
         scholarship: `Təqaüd`,
         refunds: `Geri ödənişlər`,
         prizeoraward: `Hədiyyə və ya Mükafat`,
         passiveincome: `Passiv gəlir`,
         transfer: `Transfer`,
         seeyourfinancialreport: `Maliyyə hesabatınıza baxın`,
         week: `Həftə`,
         month: `Ay`,
         year: `İl`,
         highest: `Ən yüksək`,
         lowest: `Ən aşağı`,
         newest: `Ən yeni`,
         oldest: `Ən köhnə`,
         reset: `Sıfırla`,
         filtertransaction: `Filtr Əməliyyatı`,
         filterby: `Filtrlə`,
         sortby: `Sırala`,
         category: `Kateqoriya`,
         choosecategory: `Kateqoriya seçin`,
         selected: `Seçildi`,
         apply: `Tətbiq et`,
         type: `Tip`,
         wallet: `Pul kisəsi`,
         description: `Təsvir`,
         from: `Haradan`,
         to: `Haraya`,
         edit: `Redaktə et`,
         detailtransaction: `Əməliyyat Təfərrüatı`,
         nomoneytransaction: `Pul əməliyyatı yoxdur`,
         nomoneytransactionrecently: `Bu yaxınlarda heç bir əməliyyat olmayıb`,
         today: `Bugün`,
         yesterday: `Dünən`,
         thismonth: `Bu Ay`,
         youspend: `Xərclədiniz 💸`,
         youearned: `Qazandınız 💰`,
         biggestspend: `Ən böyük xərciniz`,
         biggestincome: `Ən böyük gəliriniz`,
         proverb: `“Maliyyə azadlığı qorxudan azad olmaqdır.”`,
         proverbname: `-Robert Kiyosaki`,
         fulldetail: `Tam təfərrüata baxın`,
         financialreport: `Maliyyə Hesabatı`,
         account: `Hesab`,
         howmuch: `Nə qədər?`,
         transactionsuccess: `Əməliyyat uğurla`,
         accountsuccess: `Hesab uğurla`,
         added: `əlavə edildi`,
         updated: `yeniləndi`,
         removed: `silindi`,
         removetransactiontitle: `Əməliyyat silinsin?`,
         removetransactiondescription: `Bu əməliyyatı silmək istədiyinizə əminsiniz?`,
         yes: `Bəli`,
         no: `Xeyr`,
         username: `İstifadəçi adı`,
         settings: `Parametrlər`,
         exportdata: `Məlumat İxracı`,
         logout: `Çıxış`,
         logoutdescription: `Çıxmaq istədiyinizə əminsiniz?`,
         usernameupdated: `İstifadəçi adı uğurla yeniləndi`,
         addnewaccount: `Hesab əlavə et`,
         accounttype: `Hesab növü`,
         balance: `Balans`,
         cash: `Nağd`,
         creditcard: `Kredit kartı`,
         savings: `Qənaət`,
         investment: `İnvestisiya`,
         business: `Biznes`,
         othermiscellaneous: `Digər`,
         editaccount: `Hesabı redaktə et`,
         detailaccount: `Hesab təfərrüatı`,
         currency: `Valyuta`,
         language: `Dil`,
         theme: `Tema`,
         about: `Haqqında`,
         help: `Kömək`,
         light: `Açıq`,
         dark: `Qaranlıq`,
         usedevicetheme: `Cihaz temasını istifadə edin`,
         expensealert: `Xərc Xəbərdarlığı`,
         expensealerttext: `Xərcləriniz barədə bildiriş alın`,
         budgettext: `Büdcəniz limiti keçdikdə bildiriş alın`,
         tipsarticles: `Məsləhətlər və Məqalələr`,
         tipsarticlestext: `Kiçik və faydalı praktik maliyyə məsləhətləri`,
         home: `Ev`,
         transaction: `Əməliyyat`,
         budget: `Büdcə`,
         profile: `Profil`,
      }
   },
);

export default strings;


